### PR TITLE
Add support for creating your own toast types

### PR DESCRIPTION
**Pull request by Bobdina**
usage:
toastr.addToastType("banana");
toastr.banana("This is a banana toast. Add the 'toast-banana' class to your css to style it.")

### CODE REVIEW

**Comment by TimFerrell** [comment]
@johnpapa  - what do you think about this?  Is demand there?

Definitely not a minor release, or v3, but maybe 2.2.x?

**Comment by Bobdina** [comment]
Admittedly, banana is a silly example. Think of more expressive toast-types like 'systemmessage', 'verbose', 'loading'.
My use case was showing a toast with a spinning fa-circle-notch font-awesome icon while downloading a large file. This was a toast that had to stay on top until complete (deferred callback to remove it), and should be distinct from the already used toast types (granted, we still had warning left, but that sounded a bit silly for a download).
Another option if you do not wish to consider this change is aliasing possibly?

**Comment by TimFerrell** [comment]
I understand.

I'm open to this change. I think once we get 2.1.2 out this is something we should look into further.

**Comment by amayer5125** [comment]
I would def use this. I am developing an admin panel and custom icons/colors would be great!

**Comment by sintro** [comment]
Much better toastr.extend feature is already implemented in toastr-angular. Why does original plugin still not have this option?

**Comment by Bobdina** [comment]
@sintro, I looked at that extend feature, and you're right, it's way more flexible. It would be a great idea to backport that to the toastr library.

**Comment by TimFerrell** [comment]
@sintro, @Bobdina - give me a PR?

**Comment by Bobdina** [comment]
@TimFerrell, I'd love to, but I'm a bit swamped in work right now.

**Comment by TimFerrell** [comment]
@Bobdina @sintro - things slowed down at all?

**Comment by johnpapa** [comment]
this is nice, but nothing that cant be done via css

**Comment by TimFerrell** [comment]
Will review the feasibility of adding this for V3.

**Pull request closed without merging**
