### PR TITLE
Multi line message

### PR DESCRIPTION
**Pull request by toddtarsi**
This splits the message body along the new line characters and appends a message div for each line. Please let me know if you'd be interested in incorporating this. It makes multi line messages much nicer looking.

### CODE REVIEW

**Comment by toddtarsi** [comment]
Also, I'm willing to put in a bit of elbow grease if you folks want this to not impact existing users; I can route this behavior to a non default setting in the options object and send up as a different pull.

**Comment by TimFerrell** [comment]
Why can't this be done with pure CSS?

**Comment by toddtarsi** [comment]
I don't work as extensively in front end as I do backend, so its likely that I'm mistaken, but I wasn't sure if there was a way to implicitly cause a line break with css. A situation where I don't see how to render this nicely with the current framework is attached -

screenshot from 2015-08-27 12 18 52

**Comment by toddtarsi** [comment]
After revisiting your demo, I didn't realize you could just write html into the toast up until now. That is way awesome! Great module y'all, and I can accomplish what I need just writing in the html directly. Thanks!

**Pull request closed without merging**
