### PR TITLE
v3 update

### PR DESCRIPTION
**Pull request by SBero**
- Initial setup with mocha is working.
- Half of the unit tests are working.

### CODE REVIEW

**Comment by TimFerrell** [comment]
Thanks for all the work, @SBero !

**Comment by johnpapa** [comment]
Can you guys help me understand the plan for merging code into v3 branch?

I'd like to make sure we have a solid plan we all agree on for what is going in there as folks will be pulling it. For example, unit tests should all work and coverage should be high before we merge.

**Comment by johnpapa** [comment]
Unit tests, demo, linting, should be there .... then feature parity can be introduced slowly.

**Comment by johnpapa** [comment]
BTW - this is all GREAT work ... just want to make sure we're on the same page.

**Comment by TimFerrell** [comment]
From my perspective, once we declare the v3 branch as usual via the readme and after our own discussion, we can begin to mimic the contribution guidelines from v2: adding a v3-develop branch and continuing from there. 

The way this work started was by grabbing the v2 code, and beginning to rip out the JQ, add native DOM selectors in it's place. Along with the JQ tear out, we needed to solve for animations as well, which we did (or at least it appears so for now.)

@SBero is working on making sure that the unit tests work correctly against the updated v3 code. This should functionally be a 1:1 to v2.

**Comment by johnpapa** [comment]
cool. Once we get solid there, I'd like to introduce my gulp file changes for babel (and typescript later).

**Comment by TimFerrell** [comment]
What are you thinking in terms of gulp changes?

**Comment by johnpapa** [comment]
mostly clean up and adding in things i have in my gulp patterns repo

**Comment by TimFerrell** [comment]
Cool. Looking forward to those.

**Pull request merged**
