### PR TITLE
Removed plato

### PR DESCRIPTION
**Pull request by ShashankaNataraj**
* Removed the plato require
* Changed the log message to omit plato
* Removed the call to startPlatoVisualizer()
* Removed the startPlatoVisualizer() function also

https://github.com/CodeSeven/toastr/issues/334

### CODE REVIEW

**Comment by ShashankaNataraj** [comment]
@johnpapa @TimFerrell Is this going to get accepted?

**Comment by TimFerrell** [comment]
Please re-submit against develop branch.

**Comment by TimFerrell** [comment]
Looks good, though.

**Comment by ShashankaNataraj** [comment]
@TimFerrell will do, thanks.

**Pull request closed without merging**
