### PR TITLE
Fix/sweeping - Gulp and styles

### PR DESCRIPTION
**Pull request by johnpapa**
1. Refactored gulpfile to log, load plugins on the fly, and to produce CSS.
2. Added Styles.
3. Combined jshint and jscs
4. Combined transpile with build with styles with vet
5. npm packages are now using tilda, so we dont get broken by andy major or minor revisions

TODO:

1. tests do no work. they should run against es6 code, when fixed
2. sass needs to be fixed
3. open question about removing closure compiler. i don't think we should support that. if folks want it, they can compile it. we just provide the source
4. demo needs to be brought back to original state
5. lots of comments and dead code need to be removed

### CODE REVIEW

**Comment by johnpapa** [comment]
see my gulp patterns repo for some examples on running mocha tests in gulp and in the browser.

the gulp ones use karma but the concepts are the same.

i think we are fine merging these in and keep working towards an alpha once those TODOs are done. We should create a master checklist of TODOs and then get ready for alpha

**Comment by SBero** [comment]
Perfect, I'll be sure to check that out and figure it out.

I'll update #305 with all of the TODO items later today at some point.

Appreciate the help!! :smiley:

**Comment by TimFerrell** [comment]
I'll be available later tonight if you need a hand.

**Comment by johnpapa** [comment]
cool. can one of you merge this once you give it a once over?

**Comment by TimFerrell** [comment]
Sure.

**Comment by TimFerrell** [comment]
PR looks good. 
I'm okay with removing Closure; we can handle that in a future PR.

**Comment by tato123** [comment]
Tim / Stephen, nearly got 1 done

> tests do no work. they should run against es6 code, when fixed

As discussed in email, last remaining issue was tests for removing toasts. Problem is the visibility check

```
removeToast(toastElement) {
 ....
    if (this.isElementVisible(toastElement)) {
              return;
    }
 ...
}

isElementVisible(element) {
        return element.offsetWidth > 0 && element.offsetHeight > 0; // TODO this doesn't work
}
```

It's not clear to me what the intent of the check is and if the code should report a failure if it lands here (or whether we should pass through which would remove the toastElement without an animation). From the code it looks like this is similar to a destroy method and cleans up any dom or js references to the toast element, is that true? 

Also as two quick side notes:

1. removeToast and clearToast look like they should be private, wouldn't it be better to move these to functions outside the class and call them with the class scope bound to prevent exporting them as part of the api?

2. Wouldn't it simplify the api to merge clear and remove into a single function and just use an animated flag (i.e. like iOS)?

**Comment by TimFerrell** [comment]
Thanks for your work, @tato123.

`Remove` and `clear` actually have different intents. `remove` immediately removes it from the DOM, bypassing transitions. `clear` removes it from the DOM, while allowing transitions. One is immediate, the other is not.

**Pull request merged**
