### PR TITLE
Prevent extendedTimeOut from overriding the timeOut

### PR DESCRIPTION
**Pull request by tonyjmnz**
This PR is intended to solve #314.

It seems to be working properly for me, although I have to admit that I haven't tested it for all the different options.

**Changes:**

* If `intervalId != null` then there’s a scheduled `timeOut` interval.
* If `registeredDelay == true` there’s a scheduled `extendedTimeOut` interval.
* The `extendedTimeOut` interval checks if `intervalId == null` before hiding the toast, if it isn’t, the toast isn’t hidden.
* The `timeOut` timer checks if `registeredDelayed == true` before hiding the toast, if it isn’t, the toast isn’t hidden. (prevents the former `timeOut` interval to override a `extendedTimeOut` interval)
* The `stickAround` function no longer clears the `timeOut` interval, but the function checks for `:hover` before hiding.

**New behaviour:**

The toast isn't hidden if the added `extendedTimeOut` timer ends before the former `timeOut` timer.

### CODE REVIEW

**Comment by gray-one** [comment]
:+1:

**Comment by gray-one** [comment]
@tonyjmnz are you going to resolve conflicts and merge this fix?

**Comment by tonyjmnz** [comment]
I'd like to see it merged, but that's up to the project owners.

**Comment by johnpapa** [comment]
We've been pretty busy lately and working towards v3. So it might be a bit til we can get bandwidth to test these.

But what would help is you adding tests. Any change we make has to have a pass and fail test for it to keep the library's integrity

**Comment by tonyjmnz** [comment]
Sounds reasonable. I'll try to add them soon.

**Comment by TimFerrell** [comment]
@tonyjmnz - any update here?

**Comment by TimFerrell** [comment]
No update; PR is against incorrect branch.

**Pull request closed without merging**
