### PR TITLE
Add class options for close button and progress

### PR DESCRIPTION
**Pull request by digia**
Allow the ability to set the classes for the progress bar and close buttons.

### CODE REVIEW

**Comment by TimFerrell** [comment]
Isn't it already possible to do this through CSS directly?

**Comment by digia** [comment]
It's possible to stylize the existing classes, however you cannot change the class like you can for toastClass, containerId, iconClasses, iconClass, titleClass, and messageClass.

If you can change all the other classes, why can't you change button and progress classes?

**Comment by TimFerrell** [comment]
Valid point.

Thank you!

**Comment by digia** [comment]
Haha! NP.

Thanks.

**Pull request merged**
