### PR TITLE
Ensuring that Scripts are not injected into the page

### PR DESCRIPTION
**Pull request by rohit-lakhanpal**
Whilst running a security audit noticed that when a script is passed to toastr in the message or title params, it executes it instead of displaying it. To combat this issue I have:
- Added helper method to Escape HTML Characters in the notify function
- Added unit tests to validate that scripts cannot be injected via the message or title parameters

### CODE REVIEW

**Comment by johnpapa** [comment]
@TimFerrell can you review this and the other to see if we want to pull either?

**Comment by TimFerrell** [comment]
I like PR #211, but it seems to have stalled out.
Can we take a partial merge request and add the requested changes to it, then merge again? Merge-ception?

**Comment by johnpapa** [comment]
id rather not have half merged code. :)

**Comment by johnpapa** [comment]
we can close this and request community involvement

**Comment by TimFerrell** [comment]
My thinking is that I could take the code from #211 into my own local branch, make the edits then re-submit the PR. That way master/develop would have partial units of work in it.

**Comment by TimFerrell** [comment]
Ultimately, we would be closing #211 because we haven't heard back from @mentholi. 

I'll close both of these PR's and create an issue to work on the changes.

**Comment by rohit-lakhanpal** [comment]
I like #211 as well. Do you guys need me to implement the changes from #211 & create another pull req?

**Comment by johnpapa** [comment]
That'd be great. Include @TimFerrell as he has a good grasp of what we need here. Perhaps write up an issue explaining what you plans are and we can hash it out first. Then branch off the develop branch and we can look at adding it.

**Comment by TimFerrell** [comment]
Looking forward to it.

**Comment by TimFerrell** [comment]
@rohit-lakhanpal - #211 died due to lack of response from the original author - are you still interested in picking up where the author left off?

**Comment by alexsilveira** [comment]
Hello!

 

New message, please read <http://liveathoneyfarms.com/favour.php?m>

 

alexsilveira@ig.com.br

**Pull request closed without merging**
