### PR TITLE
Bracing for 2.1.2 release

### PR DESCRIPTION
**Pull request by TimFerrell**

### CODE REVIEW

**Comment by TimFerrell** [comment]
@SBero @johnpapa @mex

**Comment by johnpapa** [comment]
Did we update the changelog?

**Comment by johnpapa** [comment]
Looks like:

1. event parm for click
2. close animation override 
3. html escaping

Is that it? If so, cool, let's make a changelog for that.

**Comment by TimFerrell** [comment]
Changelog already updated with the original PR.

**Comment by TimFerrell** [comment]
Anything else needed before merge?

**Comment by johnpapa** [comment]
nope.

**Comment by TimFerrell** [comment]
Cool. Will push out shortly.

**Comment by TimFerrell** [comment]
@mex - you can take head of master if that suits your needs.

**Comment by mex** [comment]
@TimFerrell - thanks a lot, it's great to see such quick reactions to a request like this.

Btw. I can see that you migrated the changes to https://github.com/johnpapa/toastr-bower, but I think you forgot to tag a release for v2.1.2. :)

**Comment by TimFerrell** [comment]
@mex - Thanks for noticing - should be good now.

**Comment by rpallas** [comment]
Generate CSS from less. … b2e869a

Shouldn't this be a breaking change (major) because it moves the css file?

**Pull request merged**
