### PR TITLE
close button now has line-height 1 to stay consistent over bootstrap …

### PR DESCRIPTION
**Pull request by pickledyamsman**
…versions

### CODE REVIEW

**Comment by TimFerrell** [comment]
Thanks @pickledyamsman. Which versions of Bootstrap did you test against?

**Comment by TimFerrell** [comment]
Also, can you add a unit, please?

**Comment by pickledyamsman** [comment]
@TimFerrell adding a unit isn't required because line-height:1 uses the font-size for the unit.

**Comment by TimFerrell** [comment]
Cool. Thanks for the PR!

**Pull request merged**
