### PR TITLE
Allow generic calls to notify

### PR DESCRIPTION
**Pull request by johncongdon**
I wanted to extend different types of notifications.  And the rigidity of error, warning, info, and success didn't meet my needs.  Since these are just wrappers to notify, I thought that being able to call it directly would help my cause.

### CODE REVIEW

**Comment by johncongdon** [comment]
This is similar to #393, but allows a little more flexibility.  Especially with the iconClass parameter.

**Comment by johncongdon** [comment]
Oh wow, #273 is even better than mine.

**Comment by TimFerrell** [comment]
@johncongdon, Feel free to complete the work in progress on #273.

**Comment by TimFerrell** [comment]
Closing due to lack of demand/progress.

**Pull request closed without merging**
