### PR TITLE
Right To Left (RTL) Support 

### PR DESCRIPTION
**Pull request by mush42**
Right-to-left (RTL) support for toastr. That will enable support for languages such as Arabic.
A new option was added to toastr options (rtl), and of course, a function to add (.rtl) class to #toast-container > div.
In the css side the work is just flipping things and turning them in the other direction.
Originally I developed this for my website and thought it will be extremely useful if it is merged into the code base.

Thanks,
Musharraf Omer

### CODE REVIEW

**Comment by Behzadkhosravifar** [comment]
please solve this conflicts, I want to use rtl direction in my project.
thanks

**Comment by arahansen** [comment]
Instead of demanding things of open source contributors, who are simply volunteers and owe you nothing, might I suggest looking into the conflicts yourself and offering up an updating Pull Request?

**Comment by TimFerrell** [comment]
Thanks @arahansen. If anyone is able to resolve conflicts I'd be glad to merge in.

**Comment by TimFerrell** [comment]
Thanks to @ricardobrandao for the PR. This is now integrated to develop branch.

**Comment by mush42** [comment]
Thanks @ricardobrandao for your PR. And my apologies for all those who wanted the feature, I submitted the initial PR, but I am no longer interested in this feature, but nevertheless it will be useful for many I think.

**Pull request closed without merging**
